"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import Header from "@/components/Header";
import PdfUploader from "@/components/PdfUploader";
import ProtectedRoute from "@/components/ProtectedRoute";
import { motion } from "framer-motion";
import { Zap, Shield, BarChart3 } from "lucide-react";
import { API_URL } from "@/lib/api";
import type { ChecklistData } from "@/components/ChecklistResult";

export default function Home() {
  return (
    <ProtectedRoute>
      <HomeContent />
    </ProtectedRoute>
  );
}

function HomeContent() {
  const router = useRouter();
  const [isProcessing, setIsProcessing] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();

  const handleExtract = async (file: File) => {
    setIsProcessing(true);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const uploadRes = await fetch(`${API_URL}/documents/upload`, {
        method: "POST",
        credentials: "include",
        body: formData,
      });

      if (!uploadRes.ok) {
        const err = await uploadRes.json().catch(() => ({}));
        throw new Error((err as { message?: string }).message ?? "Falha no upload");
      }

      const { documentId } = (await uploadRes.json()) as { documentId: string };

      // Poll status until done
      let status = "pending";
      for (let i = 0; i < 120; i++) {
        const statusRes = await fetch(`${API_URL}/documents/${documentId}/status`, {
          credentials: "include",
        });
        const data = (await statusRes.json()) as { status: string };
        status = data.status;
        if (status === "done") break;
        if (status === "failed") throw new Error("Processamento do documento falhou.");
        await new Promise((r) => setTimeout(r, 2000));
      }

      if (status !== "done") {
        throw new Error("Tempo esgotado aguardando processamento.");
      }

      // Fetch the checklist generated by the worker (retry briefly in case of race)
      let checklistRes: Response | null = null;
      for (let attempt = 0; attempt < 5; attempt++) {
        checklistRes = await fetch(`${API_URL}/documents/${documentId}/checklist`, {
          credentials: "include",
        });
        if (checklistRes.ok) break;
        if (checklistRes.status === 404 && attempt < 4) {
          await new Promise((r) => setTimeout(r, 1000));
          continue;
        }
        break;
      }
      if (!checklistRes?.ok) {
        const err = await checklistRes?.json().catch(() => ({}));
        throw new Error((err as { message?: string }).message ?? "Falha ao obter checklist");
      }

      const body = (await checklistRes.json()) as { checklist: ChecklistData; checklistId?: string };
      const checklistId = body.checklistId;

      if (checklistId) {
        toast({ title: "Extração concluída!", description: "Redirecionando para o checklist..." });
        router.push(`/historico/${checklistId}`);
      } else {
        toast({
          title: "Extração concluída!",
          description: "O checklist foi gerado. Acesse o Histórico para visualizar.",
        });
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Não foi possível processar o edital. Tente novamente.";
      toast({
        title: "Erro na extração",
        description: message,
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main className="container mx-auto px-6 py-8">
        <div className="mx-auto max-w-2xl space-y-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-center space-y-4"
          >
            <h2 className="font-display text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Extraia editais em{" "}
              <span className="text-primary">minutos</span>
            </h2>
            <p className="text-lg text-muted-foreground max-w-lg mx-auto">
              Faça upload do PDF ou CSV do edital e a IA irá gerar automaticamente o checklist com todos os requisitos e documentos necessários.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <PdfUploader onExtract={handleExtract} isProcessing={isProcessing} />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="grid grid-cols-1 gap-4 sm:grid-cols-3"
          >
            <FeatureCard icon={<Zap className="h-5 w-5" />} title="Extração Rápida" description="De horas para minutos com IA" />
            <FeatureCard icon={<Shield className="h-5 w-5" />} title="95% de Precisão" description="Correspondência automática de documentos" />
            <FeatureCard icon={<BarChart3 className="h-5 w-5" />} title="Pontuação" description="Avaliação automática de oportunidades" />
          </motion.div>
        </div>
      </main>
    </div>
  );
}

function FeatureCard({
  icon,
  title,
  description,
}: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <div className="rounded-xl bg-card p-5 shadow-card border border-border text-center space-y-2">
      <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
        {icon}
      </div>
      <h3 className="font-display font-semibold text-foreground text-sm">{title}</h3>
      <p className="text-xs text-muted-foreground">{description}</p>
    </div>
  );
}
